name: chili_custom_lints
description: Chili custom lints
version: 1.1.0

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^8.4.0
  analyzer_plugin: ^0.13.0
  custom_lint_builder: ^0.8.1
  collection: any

dev_dependencies:
  lints: ^6.1.0
